model: esrgan                # "rcan" or "esrgan"
checkpoint: ./model_checkpoints/ESRGAN/X2.pth  # optional, can be null
scale: 2

# dataset paths (directory or glob). Leave empty/null to skip.
flickr_dir: ./data/Flickr2K-10k/HR
pokemon_dir: ./data/pokemons/HR