# data
ram_limit_train: 32
ram_limit_valid: 8

# model
model: rcan # rcan, esrgan_pretrain, esrgan
pretrained_path: ./tmp_model_checkpoints/ESRGAN_pretrained_X2.pth # Needed for model: "esrgan" only
scale: 2

# train
epochs: 1500
batch_size: 16
step_size: 400